# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[default]


remappings = [
  "@ds=lib/ds-test/src/",
  "@std=lib/forge-std/src/",
  "@solmate=lib/solmate/src/",
  "@clones=lib/clones-with-immutable-args/src/",
]

src = "src"
out = "out"


libs = ["node_modules"]

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000